extends Node
## The swappable asset layer. Everything asks for art by LOGICAL NAME
## (e.g. "hero.knight.idle"), never by file path — so swapping assets/manifest.json
## swaps the art without touching code. This is also the distribution escape hatch:
## the copyrighted originals stay hidden behind these logical names.
## Autoloaded as `AssetLibrary` (see project.godot).

const MANIFEST_PATH := "res://assets/manifest.json"

var _manifest: Dictionary = {}
var _cache: Dictionary = {}   # logical_name -> Texture2D (loaded once)

func _ready() -> void:
	_load_manifest()

func _load_manifest() -> void:
	if not FileAccess.file_exists(MANIFEST_PATH):
		push_warning("No asset manifest yet at %s" % MANIFEST_PATH)
		return
	var text := FileAccess.get_file_as_string(MANIFEST_PATH)
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) == TYPE_DICTIONARY:
		_manifest = parsed

## Resolve a logical name to its texture, or null if unknown/missing. Returning null is a valid
## answer, not a crash: the art is gitignored and regenerated by the Python pipeline, so a fresh
## checkout has none — callers (e.g. MapView) fall back to placeholders until it's built.
##
## Loads PNGs via Image (not load()) so externally-generated files work without Godot having
## imported them first. Results are cached.
func texture(logical_name: String) -> Texture2D:
	if _cache.has(logical_name):
		return _cache[logical_name]
	if not _manifest.has(logical_name):
		return null
	var path: String = _manifest[logical_name]
	var image := Image.load_from_file(path)
	if image == null:
		push_warning("Asset '%s' listed but unreadable at %s" % [logical_name, path])
		return null
	var tex := ImageTexture.create_from_image(image)
	_cache[logical_name] = tex
	return tex
